service: aws-node-daily-inspiration
frameworkVersion: '3'

custom:
  tableName: 'email-service-users-table-${sls:stage}'
  region: ${self:provider.region}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverless-admin
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action: SNS:Publish
          Resource: !Ref QuotesMessages
        - Effect: Allow
          Action: "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    SENDGRID_API_KEY: SG.XXXXxxxxxXXXXXXxxxxx
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:custom.region}
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:903071054357:quotes-messages-dev

functions:
  quotes:
    handler: handler/getQuotes.getQuotes
    events:
      - http:
          path: quotes
          method: GET
          cors: true
  subscribe: 
    handler: handler/subscribeUser.subscribeUser
    events:
      - http:
          path: subscribe
          method: POST
          cors: true
  staticMailer:
    handler: handler/staticMailer.staticMailer
    events:
      - http:
          path: static-mailer
          method: post
          cors: true
  sendEmail:
    handler: handler/sendEmail.sendEmail
    events:
      - http:
          path: send-email
          method: post
          cors: true
  getSubscribers:
    handler: handler/getSubscribers.getSubscribers
    events:
      - http:
          path: subscribers
          method: get
          cors: true
resources:
  Resources:
    QuotesMessages:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: quotes-messages-${self:provider.stage}
    QuotesMessagesSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref QuotesMessages
        Protocol: email
        Endpoint: vina@mailinator.com
        DeliveryPolicy:
          healthyRetryPolicy:
            numRetries: 20
            minDelayTarget: 30
            maxDelayTarget: 600
            backoffFunction: exponential
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
